apiVersion: v1
kind: Service
metadata:
  name: frontend-candidate
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: frontend
    slot: green
  ports:
    - port: 80
      targetPort: 80